//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tnt.KofaxCapture.TntCiReportingExport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tnt.KofaxCapture.TntCiReportingExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Apply.
        /// </summary>
        internal static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNT CI Reporting Export.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseScript() called before OpenScript()..
        /// </summary>
        internal static string BadCloseScriptCall {
            get {
                return ResourceManager.GetString("BadCloseScriptCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDoc() called before OpenScript()..
        /// </summary>
        internal static string BadReleaseDocCall {
            get {
                return ResourceManager.GetString("BadReleaseDocCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Class:.
        /// </summary>
        internal static string BatchClassLabelText {
            get {
                return ResourceManager.GetString("BatchClassLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string BatchFieldTypeFriendlyName {
            get {
                return ResourceManager.GetString("BatchFieldTypeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning export of document....
        /// </summary>
        internal static string BeginningExport {
            get {
                return ResourceManager.GetString("BeginningExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse.
        /// </summary>
        internal static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write text file. {0}.
        /// </summary>
        internal static string CannotWriteText {
            get {
                return ResourceManager.GetString("CannotWriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing script....
        /// </summary>
        internal static string ClosingScript {
            get {
                return ResourceManager.GetString("ClosingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine directory path of Assembly..
        /// </summary>
        internal static string CouldNotDetermineDirectoryPathOfAssembly {
            get {
                return ResourceManager.GetString("CouldNotDetermineDirectoryPathOfAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find expected file at &quot;{0}&quot;..
        /// </summary>
        internal static string CouldNotFindExpectedFile {
            get {
                return ResourceManager.GetString("CouldNotFindExpectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Class:.
        /// </summary>
        internal static string DocClassLabelText {
            get {
                return ResourceManager.GetString("DocClassLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting document: {0}.  {1}.
        /// </summary>
        internal static string ErrorExportingDocument {
            get {
                return ResourceManager.GetString("ErrorExportingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing text to final destination.  Attempt: {0}. {1}.
        /// </summary>
        internal static string ErrorWritingText {
            get {
                return ResourceManager.GetString("ErrorWritingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting settings....
        /// </summary>
        internal static string GettingSettings {
            get {
                return ResourceManager.GetString("GettingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to get report XML....
        /// </summary>
        internal static string GettingXml {
            get {
                return ResourceManager.GetString("GettingXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current settings are invalid: 
        ///
        ///{0}.
        /// </summary>
        internal static string InvalidSettings {
            get {
                return ResourceManager.GetString("InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs directory path &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string LogDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("LogDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Kofax Capture Registry key..
        /// </summary>
        internal static string MissingKofaxRegistryKey {
            get {
                return ResourceManager.GetString("MissingKofaxRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required {0} field: {1}..
        /// </summary>
        internal static string MissingRequiredField {
            get {
                return ResourceManager.GetString("MissingRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ServerPath value..
        /// </summary>
        internal static string MissingServerPathValue {
            get {
                return ResourceManager.GetString("MissingServerPathValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NextPage {
            get {
                object obj = ResourceManager.GetObject("NextPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report XML does not exist..
        /// </summary>
        internal static string NoReportXml {
            get {
                return ResourceManager.GetString("NoReportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening script....
        /// </summary>
        internal static string OpeningScript {
            get {
                return ResourceManager.GetString("OpeningScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory cannot be blank..
        /// </summary>
        internal static string OutputDirectoryCannotBeBlank {
            get {
                return ResourceManager.GetString("OutputDirectoryCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the output directory..
        /// </summary>
        internal static string OutputDirectoryFolderBrowserDialogDescription {
            get {
                return ResourceManager.GetString("OutputDirectoryFolderBrowserDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory:.
        /// </summary>
        internal static string OutputDirectoryLabelText {
            get {
                return ResourceManager.GetString("OutputDirectoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        internal static string OutputDirectoryText {
            get {
                return ResourceManager.GetString("OutputDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &quot;{1}&quot; does not exist..
        /// </summary>
        internal static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrevPage {
            get {
                object obj = ResourceManager.GetObject("PrevPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing batch &quot;{0}&quot;....
        /// </summary>
        internal static string ProcessingBatch {
            get {
                return ResourceManager.GetString("ProcessingBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing document {0}....
        /// </summary>
        internal static string ProcessingDocumentN {
            get {
                return ResourceManager.GetString("ProcessingDocumentN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; &amp;Remove.
        /// </summary>
        internal static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required setting &quot;{0}&quot; has no value..
        /// </summary>
        internal static string RequiredSettingMissing {
            get {
                return ResourceManager.GetString("RequiredSettingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save the current settings?.
        /// </summary>
        internal static string SettingsChangedSave {
            get {
                return ResourceManager.GetString("SettingsChangedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown Assembly Value&gt;.
        /// </summary>
        internal static string UnknownAssemblyValue {
            get {
                return ResourceManager.GetString("UnknownAssemblyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported generic type: {0}..
        /// </summary>
        internal static string UnsupportedGenericType {
            get {
                return ResourceManager.GetString("UnsupportedGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionLabelText {
            get {
                return ResourceManager.GetString("VersionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing text to &quot;{0}&quot;....
        /// </summary>
        internal static string WritingTextFile {
            get {
                return ResourceManager.GetString("WritingTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing XML to &quot;{0}&quot;....
        /// </summary>
        internal static string WritingXml {
            get {
                return ResourceManager.GetString("WritingXml", resourceCulture);
            }
        }
    }
}
